version: '3.8'

services:
  cultural-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cultural-agent-container
    volumes:
      - ./outputs:/app/outputs          # Store evaluation_chart.png outside container
      - ./logs:/app/logs                # Save logs
    environment:
      PYTHONUNBUFFERED: 1               # Force real-time logging
      OLLAMA_HOST: http://host.docker.internal:11434 # Connect to Ollama on Docker host
    entrypoint: >
      bash -c "
        echo '🧹 Cleaning old outputs...' &&
        rm -f /app/outputs/evaluation_chart.png /app/logs/run.log &&
        echo '🚀 Installing requirements...' &&
        pip install -r requirements.txt && \
        echo '🚀 Starting system...' &&
        python main.py | tee /app/logs/run.log
      "
