version: '3.8'

services:
  cultural-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cultural-agent-container
    volumes:
      - ./outputs:/app/outputs          # Store evaluation_chart.png outside container
      - ./logs:/app/logs                # Save logs
    environment:
      PYTHONUNBUFFERED: 1               # Force real-time logging
    ports:
      - "8000:8000"
    env_file:
      - .env
  ollama-gpu:
    image: ollama/ollama:latest
    container_name: ollama-gpu-container
    gpus: all
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  ollama:
    external: false
